### ISSUE TITLE
Volto Heading Block is not taken into account by Volto Core ToC Block

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-heading-block#11]
When adding a Heading Block to a page that uses the Volto Core Table-of-Contents (ToC) block, the heading block headlines do not show up.

I guess we need some kind of hook into the ToC block.

@sneridagh is that something that we can ask @danalvrz to work on? cc @davisagli

**Comment by davisagli** [comment]
@tisto @sneridagh The ToC block already has a way to configure a different way to return entries for the table of contents for each block type. I can point @danalvrz in the right direction on this.
